version: 1
sequences:
- protein:
    id: H
    sequence: EVQLLESGGGLVQPGGSLRLSCAASGLTFRSYAMTWVRQAPGKGLEWVSGISVSGGITYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKRGAAVGSFDYWGQGTLVTVSS
    msa: hackathon_data/datasets/abag_public/msa/8CYH_0.csv
- protein:
    id: L
    sequence: DIQMTQSPSSLSASVGDRVTITCRSSQGIGSWLAWYQQKPEKAPQSLIYAASSLQSGVPSRFSGSGSGTDFTLTISNLQPEDFATYYCQQYNSYPLTFGGGTKVEIK
    msa: hackathon_data/datasets/abag_public/msa/8CYH_1.csv
- protein:
    id: A
    sequence: EVEKTACPSGKKAREIDESLIFYKKWELEACVDAALLATQMDRVNAIPFTYEQLDVLKHKLDELYPQGYPESVIQHLGYLFLKMSPEDIRKWNVTSLETLKALLEVNKGHEMSPQAPRRPLPQVATLIDRFVKGRGQLDKDTLDTLTAFYPGYLCSLSPEELSSVPPSSIWAVRPQDLDTCDPRQLDVLYPKARLAFQNMNGSEYFVKIQSFLGGAPTEDLKALSQQNVSMDLATFMKLRTDAVLPLTVAEVQKLLGPHVEGLKAEERHRPVRDWILRQRQDDLDTLGLGLQGGIPNGYLVLDLSMQEALGSGLNDIFEAQKIEWHE
    msa: hackathon_data/datasets/abag_public/msa/8CYH_2.csv
